# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_BASE_URL=http://backend:3001

  cypress:
    image: cypress/included:latest
    working_dir: /e2e
    network_mode: host
    command: sh -c "cypress run"
    entrypoint: []
    depends_on:
      - frontend
      - backend
    volumes:
      - ./frontend:/e2e:z


  backend:
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - mongo-express
    environment:
      - PORT=3001
      - MONGODB_URL=mongodb://root:example@mongo:27017/